#!/usr/bin/env bash
set -euo pipefail

python experiments/constraints/run_nested_calibration.py
python experiments/constraints/run_carrier_robustness.py
python experiments/constraints/run_prospective_role_transfer.py

python experiments/information_selection/run_bellman_vs_myopic.py
python experiments/information_selection/run_noisy_sources.py
python experiments/information_selection/run_cost_sensitivity.py
python experiments/information_selection/run_exact_scaling.py
python experiments/information_selection/run_reliability_sweep.py

python scripts/verify_reference_results.py
